[2020-06-12 15:59:51,864] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [queued]>
[2020-06-12 15:59:51,908] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [queued]>
[2020-06-12 15:59:51,909] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-12 15:59:51,909] {taskinstance.py:880} INFO - Starting attempt 19 of 22
[2020-06-12 15:59:51,909] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-12 15:59:51,932] {taskinstance.py:900} INFO - Executing <Task(BashOperator): modeling> on 2020-06-11T00:00:00+00:00
[2020-06-12 15:59:51,935] {standard_task_runner.py:53} INFO - Started process 29601 to run task
[2020-06-12 15:59:52,002] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dataops.modeling 2020-06-11T00:00:00+00:00 [running]> vinicius-Latitude-3480
[2020-06-12 15:59:52,026] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-06-12 15:59:52,027] {bash_operator.py:103} INFO - Temporary script location: /tmp/airflowtmpkhy7nj9i/modelingq5iuny6f
[2020-06-12 15:59:52,027] {bash_operator.py:115} INFO - Running command: python /home/vinicius/Documents/Projetos/Claro/Piloto/git_Homologação/src/modeling/run.py
[2020-06-12 15:59:52,032] {bash_operator.py:122} INFO - Output:
[2020-06-12 16:00:56,058] {bash_operator.py:126} INFO - Treinando modelo KN_Test_2
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO - Traceback (most recent call last):
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -   File "/home/vinicius/Documents/Projetos/Claro/Piloto/git_Homologação/src/modeling/run.py", line 103, in <module>
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -     save_mlflow(model,result,config_model,model_name)
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -   File "/home/vinicius/Documents/Projetos/Claro/Piloto/git_Homologação/src/modeling/run.py", line 32, in save_mlflow
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -     mlflow.sklearn.log_model(model,artifact_path=f"{data_path}/model/{str(model_id)}_log")
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -   File "/home/vinicius/anaconda3/envs/claro_piloto_homolog/lib/python3.8/site-packages/mlflow/sklearn.py", line 206, in log_model
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -     return Model.log(artifact_path=artifact_path,
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -   File "/home/vinicius/anaconda3/envs/claro_piloto_homolog/lib/python3.8/site-packages/mlflow/models/__init__.py", line 102, in log
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -     mlflow.tracking.fluent.log_artifacts(local_path, artifact_path)
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -   File "/home/vinicius/anaconda3/envs/claro_piloto_homolog/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 323, in log_artifacts
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -     MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -   File "/home/vinicius/anaconda3/envs/claro_piloto_homolog/lib/python3.8/site-packages/mlflow/tracking/client.py", line 267, in log_artifacts
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -     self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -   File "/home/vinicius/anaconda3/envs/claro_piloto_homolog/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 268, in log_artifacts
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -     artifact_repo.log_artifacts(local_dir, artifact_path)
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -   File "/home/vinicius/anaconda3/envs/claro_piloto_homolog/lib/python3.8/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 42, in log_artifacts
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -     verify_artifact_path(artifact_path)
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -   File "/home/vinicius/anaconda3/envs/claro_piloto_homolog/lib/python3.8/site-packages/mlflow/store/artifact/artifact_repo.py", line 167, in verify_artifact_path
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO -     raise MlflowException("Invalid artifact path: '%s'. %s" % (artifact_path,
[2020-06-12 16:00:56,059] {bash_operator.py:126} INFO - mlflow.exceptions.MlflowException: Invalid artifact path: '/home/vinicius/Documents/Projetos/Claro/Piloto/git_Homologação/data/model/f275679f5c2b4af0b53db1186e7e1f6a_log'. Names may be treated as files in certain cases, and must not resolve to other names when treated as such. This name would resolve to '/home/vinicius/Documents/Projetos/Claro/Piloto/git_Homologação/data/model/f275679f5c2b4af0b53db1186e7e1f6a_log'
[2020-06-12 16:00:56,386] {bash_operator.py:128} INFO - Command exited with return code 1
[2020-06-12 16:00:56,398] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/vinicius/anaconda3/envs/claro_piloto_homolog/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/vinicius/anaconda3/envs/claro_piloto_homolog/lib/python3.8/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-06-12 16:00:56,400] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-12 16:00:57,291] {logging_mixin.py:112} INFO - [2020-06-12 16:00:57,290] {local_task_job.py:103} INFO - Task exited with return code 1
